-- CreateEnum
CREATE TYPE "Role" AS ENUM ('CUSTOMER', 'ADMIN');

-- CreateEnum
CREATE TYPE "ReservationStatus" AS ENUM ('PENDING_PAYMENT', 'CONFIRMED', 'CANCELLED', 'EXPIRED');

-- CreateEnum
CREATE TYPE "PaymentStatus" AS ENUM ('UNPAID', 'PAID', 'REFUNDED', 'FAILED');

-- CreateTable
CREATE TABLE "profiles" (
    "id" UUID NOT NULL,
    "username" TEXT NOT NULL,
    "avatar_url" TEXT,
    "role" "Role" NOT NULL DEFAULT 'CUSTOMER',
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "profiles_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "courts" (
    "id" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "price_uah" INTEGER NOT NULL,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "sort_order" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "courts_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "reservations" (
    "id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "court_id" UUID NOT NULL,
    "date" DATE NOT NULL,
    "start_time" TEXT NOT NULL,
    "end_time" TEXT NOT NULL,
    "start_at" TIMESTAMP(3) NOT NULL,
    "end_at" TIMESTAMP(3) NOT NULL,
    "status" "ReservationStatus" NOT NULL DEFAULT 'PENDING_PAYMENT',
    "payment_status" "PaymentStatus" NOT NULL DEFAULT 'UNPAID',
    "order_reference" TEXT NOT NULL,
    "amount_uah" INTEGER NOT NULL,
    "expires_at" TIMESTAMP(3) NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "reservations_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "payments" (
    "id" UUID NOT NULL,
    "reservation_id" UUID NOT NULL,
    "provider" TEXT NOT NULL DEFAULT 'wayforpay',
    "order_reference" TEXT NOT NULL,
    "amount_uah" INTEGER NOT NULL,
    "status" TEXT NOT NULL,
    "raw_payload" JSONB NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "payments_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "auth_attempts" (
    "id" UUID NOT NULL,
    "key" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "auth_attempts_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "profiles_username_key" ON "profiles"("username");

-- CreateIndex
CREATE UNIQUE INDEX "reservations_order_reference_key" ON "reservations"("order_reference");

-- CreateIndex
CREATE INDEX "reservations_user_id_idx" ON "reservations"("user_id");

-- CreateIndex
CREATE INDEX "reservations_court_id_date_idx" ON "reservations"("court_id", "date");

-- CreateIndex
CREATE INDEX "payments_reservation_id_idx" ON "payments"("reservation_id");

-- CreateIndex
CREATE INDEX "auth_attempts_key_created_at_idx" ON "auth_attempts"("key", "created_at");

-- AddForeignKey
ALTER TABLE "reservations" ADD CONSTRAINT "reservations_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "profiles"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "reservations" ADD CONSTRAINT "reservations_court_id_fkey" FOREIGN KEY ("court_id") REFERENCES "courts"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "payments" ADD CONSTRAINT "payments_reservation_id_fkey" FOREIGN KEY ("reservation_id") REFERENCES "reservations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- ============================================================================
-- Hand-added below: not generated by Prisma (its schema language can't
-- express these) — see ARCHITECTURE.md §4.1-§4.3 and §5.
-- ============================================================================

-- profiles.id is the same UUID as Supabase's own auth.users.id (1:1).
-- Prisma doesn't manage auth.users, so this FK is added by hand.
ALTER TABLE "profiles"
  ADD CONSTRAINT "profiles_id_fkey"
  FOREIGN KEY ("id") REFERENCES auth.users(id) ON DELETE CASCADE;

-- The actual double-booking guard: at most one PENDING_PAYMENT/CONFIRMED
-- reservation per (court, start time), enforced atomically by Postgres
-- regardless of application-level races. See ARCHITECTURE.md §7.
CREATE UNIQUE INDEX "reservations_court_slot_active_uidx"
  ON "reservations" ("court_id", "start_at")
  WHERE status IN ('PENDING_PAYMENT', 'CONFIRMED');

-- Creates the matching profiles row the moment Supabase Auth creates a user,
-- so account creation and profile creation are atomic. The registration
-- flow (M2) passes the chosen username via raw_user_meta_data; the
-- coalesce fallback (email prefix + id suffix, to avoid a unique-constraint
-- collision) only matters if that's ever missing.
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (id, username)
  VALUES (
    NEW.id,
    COALESCE(
      NEW.raw_user_meta_data ->> 'username',
      split_part(NEW.email, '@', 1) || '_' || substr(NEW.id::text, 1, 8)
    )
  );
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- Row Level Security — defense-in-depth. Primary authorization is enforced
-- in Next.js API route handlers (Prisma's connection bypasses RLS by
-- design); these policies protect data if the anon key were ever used
-- directly against Supabase's REST/Realtime API. See ARCHITECTURE.md §4.2.
ALTER TABLE "profiles"      ENABLE ROW LEVEL SECURITY;
ALTER TABLE "courts"        ENABLE ROW LEVEL SECURITY;
ALTER TABLE "reservations"  ENABLE ROW LEVEL SECURITY;
ALTER TABLE "payments"      ENABLE ROW LEVEL SECURITY;
ALTER TABLE "auth_attempts" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "profile_select_own" ON "profiles"
  FOR SELECT USING (auth.uid() = id);
CREATE POLICY "profile_update_own" ON "profiles"
  FOR UPDATE USING (auth.uid() = id) WITH CHECK (auth.uid() = id);

CREATE POLICY "court_select_active" ON "courts"
  FOR SELECT USING (is_active = true);

CREATE POLICY "reservation_select_own" ON "reservations"
  FOR SELECT USING (auth.uid() = user_id);

-- No policies at all for "payments" / "auth_attempts": default-deny for the
-- authenticated/anon roles, service-role (server) access only.
